<?php
/**
 * XSOS - Sistema de gestão Ordem de Serviço
 * Copyright (C) 2008  Ivan Ogassavara  
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @license    http://www.gnu.org/licenses    GNU License
 * @copyright  Copyright (C) 2008  Ivan Ogassavara
 * @category   mascara
 * @package    sos
 * @subpackage sos.mascara
 * @version    Release: @package_version@
 * @author     Ivan Ogassavara <ivan.ogassavara@gmail.com>
 */

session_unset();
?>
<div>
<form name="frmSos" action="sos.php" method="post">
    <input type="hidden" name="entidade" value="sos" />
    <input type="hidden" name="pedido" value="entrar" />
    
    <br />
    
    <table>
    <tr>
        <td>
            <font class="subTitulo">usu&aacute;rio:</font> 
        </td>
        <td>
            <input type="text" name="usuario" />
        </td>
    </tr>
    <tr>
        <td>
            <font class="subTitulo">palavra-chave: </font>
        </td>
        <td>
            <input type="password" name="senha" />
        </td>
    </tr>
    <tr>
        <td colspan="2" align="center">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="2" align="center"><input type="submit" value="Login" /></td>
    </tr>
    </table>
    <br/>
</form>
</div>
<script type="text/javascript">
    document.frmSos.usuario.focus();
</script>