<?php
/**
 * XSOS - Sistema de gestão Ordem de Serviço
 * Copyright (C) 2008  Ivan Ogassavara  
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @license    http://www.gnu.org/licenses    GNU License
 * @copyright  Copyright (C) 2008  Ivan Ogassavara
 * @category   mascara
 * @package    sos
 * @subpackage sos.mascara
 * @version    Release: @package_version@
 * @author     Ivan Ogassavara <ivan.ogassavara@gmail.com>
 */
?>

<link rel="StyleSheet" href="<?php 
    echo SosXaman::pegaAldeiaMascara(
        'estrutura/enfeite/fabricante.css');?>" 
    type="text/css"/>

<script src="estrutura/rotina/fabricanteFlx.js" charset="UTF-8"></script>

<form action="xaman.php" method="post">
<input type="hidden" name="entidade" value="">
<input type="hidden" name="pedido" value="">
<input type="hidden" name="identificador" value="">
<script>
function pesquisar(){
    document.forms[0].entidade.value="fabricante";
    document.forms[0].pedido.value="pesquisar";
    document.forms[0].identificador.value="";
    document.forms[0].submit();
}
function incluir(){
    document.forms[0].entidade.value="fabricante";
    document.forms[0].pedido.value="incluir";
    document.forms[0].submit();
}
function alterar(codigo){
    document.forms[0].entidade.value="fabricante";
    document.forms[0].pedido.value="alterar";
    document.forms[0].identificador.value=codigo;
    document.forms[0].submit();
}
function excluir(codigo){
    if (confirm("Deseja excluir o registro selecionado?")){
        document.forms[0].entidade.value="fabricante";
        document.forms[0].pedido.value="excluir";
        document.forms[0].identificador.value=codigo;
        document.forms[0].submit();
    }
}
</script>
<table width="100%" cellspacing="0" cellpadding="1" border="0">
<tr>
    <td class="body" colspan="3">
        <b>Cadastro de Fabricantes</b>
    </td>
</tr>
<tr>
    <td>
        &nbsp;
    </td>
</tr>
<tr>
    <td colspan="6">
        <table cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <td valign="top">
                <input type="button" value="Incluir Novo" onClick="javascript:incluir();">
            </td>
            <td align="right">
                <select name="pesquisa">
                    <option value="nome">Nome</option>
                </select>
                <input type="text" name="valpesquisa">
                <input type="button" value="Pesquisar" onclick="javascript:pesquisar();">
                <br>&nbsp;
            </td>
        </tr>
        </table>
    </td>
</tr>
<tr class="linhatitulo">
    <td>
        <?echo HtmlGui::lista($fabricanteVctBox, array('Nome' => 'Nome'), 3);?>
    </td>
</tr>
<tr><td>&nbsp;</td></tr>
<tr>
        <td colspan="6">
            <input type="button" value="Incluir Novo" onClick="javascript:incluir();">
        </td>
</tr>
</table>
</form>