<?php
/**
 * XSOS - Sistema de gestão Ordem de Serviço
 * Copyright (C) 2008  Ivan Ogassavara  
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @license    http://www.gnu.org/licenses    GNU License
 * @copyright  Copyright (C) 2008  Ivan Ogassavara
 * @category   mascara
 * @package    sos
 * @subpackage sos.mascara
 * @version    Release: @package_version@
 * @author     Ivan Ogassavara <ivan.ogassavara@gmail.com>
 */
?>
<link rel="StyleSheet" href="<?php echo $SOS_MASCARA
        . 'estrutura/enfeite/relatorio.css';?>" 
    type="text/css"/>
    
<script type="text/javascript"
  src="estrutura/ferramenta/RelatorioFlx.js" 
  charset="<?php echo $SOS_LINGUA;?>">
</script>

<form name="frmSos" action="sos.php" method="post">

<input type="hidden" name="entidade" value="cliente">
<input type="hidden" name="pedido" value="pesquisar">
<input type="hidden" name="identificador" value="">

<div class="subTitulo">
    Relat&oacute;rio
</div>
<div>
  <br />
  NOVO | 
  <a href="javascript:relatorioFlx.consulta('tabela');">
    LISTA DE RELAT&Oacute;RIOS
  </a>
  <br />
  &nbsp;
</div>
<div style="float:left;width:150px;border-right:5px solid #dfdfdf;
  margin-right:5px;">
  
  <select name="tabela" 
  id="slcTabela" 
  multiple="multiple"></select>
  
  <input type="button" onclick="relatorioFlx.consulta('campo');" 
    value="adiciona tabela" />
  </div>
  
<div id="capaCampo" style="float:left;width:700px;
  vertical-align:top;overflow:scroll;"></div>
</form>

<script type="text/javascript" charset="<?php echo $SOS_LINGUA; ?>">
$(document).ready(function () {relatorioFlx.consulta('tabela');});
</script>