<?php
/**
 * XSOS - Sistema de gestão Ordem de Serviço
 * Copyright (C) 2008  Ivan Ogassavara  
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @license    http://www.gnu.org/licenses    GNU License
 * @copyright  Copyright (C) 2008  Ivan Ogassavara
 * @category   mascara
 * @package    sos
 * @subpackage sos.mascara
 * @version    Release: @package_version@
 * @author     Ivan Ogassavara <ivan.ogassavara@gmail.com>
 */
?>

<link rel="StyleSheet" href="<?php echo $SOS_MASCARA
        . 'estrutura/enfeite/atendente.css';?>" 
    type="text/css"/>
    
<script src="estrutura/ferramenta/AtendenteFlx.js" 
  type="text/javascript"
  charset="<?php echo $SOS_LINGUA;?>">
</script>

<form
  id="frmSos"
  name="frmSos"
  action="javascript:atendenteFlx.armazena();" 
  method="post">

<input type="hidden" name="entidade" value="atendente">
<input type="hidden" name="pedido" value="armazenar">
<input type="hidden" name="identificador" value="<?php echo $atendenteMdl->pegaId();?>">

<table cellspacing="0" cellpadding="0" border="0">
<tr>
    <td class="subTitulo" valign="top">
        Cadastro de Atendentes
    </td>
</tr>
<tr>
    <td>
        &nbsp;
    </td>
</tr>

<tr>
    <td>
        <table>
        <tr>
            <td>
                <font class="texto">Nome: </font>
            </td>
            <td>
                <input type="text" name="nome" maxlength=60 style="width:300px;"
                    value="<?php echo $atendenteMdl->pegaNome();?>">
            </td>
        </tr>
        <tr>
            <td>
                    <font class="texto">Login: </font>
            </td>
            <td>
                <input type="text" name="login" maxlength=10 
                    value="<?php echo $atendenteMdl->pegaLogin();?>">
            </td>
        </tr>
        <tr>
            <td>
                    <font class="texto">Grupo: </font>
            </td>
            <td>
                <select name='grupo'>
                  <option value='publico' <?php 
                    echo $atendenteMdl->pegaGrupo() == 'publico' 
                      ? ' selected="selected"' : '';?>>p&uacute;blico</option>
                  <option value='admin' <?php 
                    echo $atendenteMdl->pegaGrupo() == 'admin' 
                      ? ' selected="selected"' : '';?>>administrador</option>
                </select>
            </td>
        </tr>
        <tr>
            <td>
                    <font class="texto">Senha: </font>
            </td>
            <td>
                <input type="password" name="senha" maxlength=10 
                    value="<?php echo $atendenteMdl->pegaSenha();?>">
            </td>
        </tr>
        <tr>
            <td>
                <font class="texto">Confirmar Senha: </font>
            </td>
            <td>
                <input type="password" name="resenha" maxlength=10 
                    value="<?php echo $atendenteMdl->pegaSenha();?>">
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;
            </td>
        </tr>
        <tr>
            <td colspan=2 align="center">
                <input type="button" value="Armazenar"
                    onclick="javascript:atendenteFlx.armazena();" />
                <input type="button" value="Cancelar" 
                    onclick="javascript:atendenteFlx.cancela();" />
            </td>
        </tr>
        </table>
    </td>
</tr>
</table>

</form>
<script>
$(document).ready(function () {document.frmSos.nome.focus();});
</script>